---
title: "Publications Analysis"
author: "Camila Vargas"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(stringr)
library(readxl)
library(tidytext)
library(wordcloud)

```

## Read table
```{r}
all_papers <- read_excel("data/palmyra_papers_test_0523.xlsx", sheet = "palmyra_publications")
```

## Explore
```{r}

pubs_year <- all_papers %>% 
  group_by(publication_year) %>% 
  tally() %>% 
  arrange(desc(publication_year))

first_auth <- all_papers %>% 
  mutate(first_author = word(author, 1, sep = ",")) %>% 
  mutate(first_author = recode(first_author,
                               "Baumann" = "Baumann-Pickering",
                               "Davis K" = "Davis",
                               "Edwards CB et al." = "Edwards CB",
                               "Edwards" = "Edwards CB",
                               "Houlbrèque" = "Houlbreque",
                               "Miller-Ter Kuile A" = "Miller Ter Kuile",
                               "S. Knapp" = "Knapp",
                              "Vidal-Martínez" = "Vidal-Martinez",
                              "Maragos J.E." = "Maragos")) %>% 
  group_by(first_author) %>% 
  tally()

journal <- all_papers %>% 
  mutate(journal_title = str_to_title(journal_title),
         journal_title = recode(journal_title,
                "Encyclopedia Of Modern Coral Reefs: Structure, Form And Process" = "Encyclopedia Of Modern Coral Reefs",
                "Journal Of Fish Biology," = "Journal Of Fish Biology",
                "Proceedings Of The Royal Society B: Biological Sciences" = "Proceedings Of The Royal Society B",
               "Proceedings Of The Royal Society" = "Proceedings Of The Royal Society B")) %>% 
  group_by(journal_title) %>% 
  tally() %>% 
  mutate(perc = (n/196)*100)

```



## Visualize
3 graphs

1. pubs through the years
    - Need to filter years between 2002 and 2022
    
```{r}

pal_antique <- rev(c("#855C75", "#D9AF6B", "#AF6458", "#736F4C", "#526A83", "#625377", "#68855C", "#9C9C5E", "#A06177", "#8C785D", "#467378", "#7C7C7C"))

pal_prism <- rev(c("#5F4690", "#1D6996", "#38A6A5", "#0F8554", "#73AF48", "#EDAD08", "#E17C05", "#CC503E", "#94346E", "#6F4070", "#994E95", "#666666"))

pal_pastel <-  rev(c("#66C5CC", "#F6CF71", "#F89C74", "#DCB0F2", "#87C55F", "#9EB9F3", "#FE88B1", "#C9DB74", "#8BE0A4", "#B497E7", "#D3B484", "#B3B3B3"))

pal_safe <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

pal_vivid <- c("#E58606", "#5D69B1", "#52BCA3", "#99C945", "#CC61B0", "#24796C", "#DAA51B", "#2F8AC4", "#764E9F", "#ED645A", "#CC3A8E", "#A5AA99")


all_papers %>% 
  filter(publication_year > 2000) %>% 
  ggplot(aes(x = publication_year, fill = pub_type))+ 
  geom_bar()+ #fill = "#096a82"
  scale_x_continuous(breaks = seq(2002,2022, 1))+
  scale_fill_manual(values = pal_antique)+
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))+
  labs(x = "Year",
       y = "Number of Publications",
       title = "Publications about Palmyra Atoll by type")

```

2. Authors count

Top 12 first authors publications

```{r}

first_auth %>% 
  filter(!is.na(first_author)) %>% 
  top_n(5) %>% 
  ggplot(aes(x = reorder(first_author, n),
             y = n))+
  geom_bar(stat="identity",
           fill = "#615f8b")+
  theme_classic()+
  coord_flip()+
  #scale_y_continuous(breaks = seq(0,16, 4))+ 
  labs(x = "Author's Last Name",
       y = "Number of Publications",
       title = "Researchers with most 1st-author publications")

```


3. Journals

```{r}
journal %>% 
  top_n(10) %>% 
  ggplot(aes(x = reorder(journal_title, n),
             y = n))+
  geom_bar(stat="identity",
           fill = "#096a82")+
  theme_classic()+
  coord_flip()+
  #scale_y_continuous(breaks = seq(0,16, 4))+ 
  labs(x = "Journal Title",
       y = "Number of Publications",
       title = "Top 10 Journals where Palmyra papers are published")

  
  
```


## Keyword analysis

We want to analyze title, keywords and abstract

1. Titles

```{r}

data("stop_words")

## Data Frame
title_text <- all_papers %>% 
  select(title) %>% 
  unnest_tokens(word, title) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = T)

## Plot
title_text %>%
  top_n(15) %>% 
  ggplot(aes(x = reorder(word, n),
             y = n))+
  geom_bar(stat="identity",
           fill = "#E58606")+
  theme_classic()+
  coord_flip()+
  #scale_y_continuous(breaks = seq(0,16, 4))+ 
  labs(x = "Title Words",
       y = "Count",
       title = "Top 15 words mentioned in Palmyra's publications title")
  
```


2. Keywords

```{r}

##Table

keyword_text <-  all_papers %>% 
  select(Keywords) %>% 
  unnest_tokens(word, Keywords) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = T)


## filter out keywords and all that were mention just once

## Plot
keyword_text %>%
  filter(word != "keywords") %>% 
  top_n(15) %>% 
  ggplot(aes(x = reorder(word, n),
             y = n))+
  geom_bar(stat="identity",
           fill = "#096a82")+
  theme_classic()+
  coord_flip()+
  #scale_y_continuous(breaks = seq(0,16, 4))+ 
  labs(x = "Keywords",
       y = "Count",
       title = "Top 15 Keywords in Palmyra's publications")

```


3. Abstract

**Note:** See how to fix plurals! eg: Coral and Corals

```{r}
abstract_text <- all_papers %>% 
  select(Abstract) %>% 
  unnest_tokens(word, Abstract) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = T) %>% 
  with(wordcloud(word, n, max.words = 100))
```



